# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webserver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('power', models.CharField(max_length=20, verbose_name='权限')),
            ],
            options={
                'db_table': 'cabinet',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=20, verbose_name='服务名称')),
                ('pid', models.IntegerField(verbose_name='pid')),
                ('module_letter', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_ip', models.CharField(max_length=50, verbose_name='内网IP地址')),
                ('ext_ip', models.CharField(max_length=50, verbose_name='外网IP地址')),
                ('mac_address', models.CharField(max_length=50, verbose_name='MAC地址')),
                ('hostname', models.CharField(max_length=50, verbose_name='主机名')),
                ('os', models.CharField(max_length=50, verbose_name='系统')),
                ('status', models.IntegerField(verbose_name='状态')),
                ('gateway', models.CharField(max_length=50, verbose_name='网关')),
                ('cpu_model', models.CharField(max_length=100, verbose_name='CPU型号')),
                ('cpu_thread_number', models.PositiveIntegerField(verbose_name='CPU线程数')),
                ('server_disk', models.CharField(max_length=20, verbose_name='磁盘')),
                ('server_mum', models.IntegerField(verbose_name='内存')),
                ('manufacture_date', models.DateField(verbose_name='生产日期')),
                ('manufacturers', models.CharField(max_length=30, verbose_name='生产商')),
                ('cabinet_id', models.IntegerField(verbose_name='机柜ID')),
                ('server_run', models.CharField(max_length=30, verbose_name='运行的服务')),
            ],
            options={
                'db_table': 'server',
            },
        ),
    ]
